config/routes.rb
Rails.application.routes.draw do


  resources :topics do
    resources :posts, except: [:index]
    resources :sponsored_posts, except: [:index]
  end
  resources :posts, only: [] do

    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end
  resources :advertisements

  resources :questions

  resources :users, only: [:new, :create, :show]
  post 'users/confirm' => 'users#confirm'

  resources :sessions, only: [:new, :create, :destroy]

  get 'about' => 'welcome#about'
#  get 'welcome/contact'

  get 'welcome/faq'

  root "welcome#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
# You advertisement show view depends on their being an advertisement made, and you don't seed the db with any advertisements
#
#
# [12:13]
# and for the other one i think it is because you don't define an index
#
#
# [12:16]
# and for you to make an advertisements view with resources it needs to be `resources advertisements` not `resources: advertisement`

app/models/question.rb
class Question < ApplicationRecord

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions =  Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def edit
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new
    @question.title = params[:question][:title]
    @question.body = params[:question][:body]

    if @question.save
      flash[:notice] = "Question was saved"
      redirect_to @question
    else
      flash.now[:alert] = "The question was not saved, please try again."
      render :new
    end
  end

  def update
    @question = Question.find(params[:id])

    @question.title = params[:question][:title]
    @question.body = params[:question][:body]

    if @question.save
      flash[:notice] = "The Question was updated"
      redirect_to @question
    else
      flash.now[:alert] = "The question was not save. Try again."
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])

    if @question.destroy
      flash[:notice] = "\"#{@question.title}\" was successfully deleted."
      redirect_to questions_path
    else
      flash[:alert] = "There was an error deleting the question."
      render :show
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/create.html.erb
<h1>Questions#create</h1>
<p>Find me in app/views/questions/create.html.erb</p>

app/views/questions/destroy.html.erb
<h1>Questions#destroy</h1>
<p>Find me in app/views/questions/destroy.html.erb</p>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<div class="row">
  <div class="col-md-4">
    <p>Ground rules</p>
    <ol>
      <li>Make the question legible.</li>
      <li>Do not ask anything you know the answer to.</li>
      <li>Play nice with others if applicable.</li>
    </ol>
  </div>
  <div class="col-md-8">
    <%= form_for @question do |q| %>
      <div class="form-group">
        <%= q.label :title %>
        <%= q.text_field :title, class: 'form-control', placeholder: "Enter the updates for the question" %>
      </div>
      <div class="form-group">
        <%= q.label :body %>
        <%= q.text_area :body, rows: 8, class: "form-control", placeholder: "Enter the updated question" %>
      </div>
      <div class="form-group">
        <%= q.label :resolved, class: 'checkbox' do %>
          <%= q.check_box :resolved %> Resolved
        <% end %>
      </div>
      <%= q.submit "Save", class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/questions/index.html.erb
<h1>Questions</h1>
<div class="row">
  <div class="col-md-8">


    <% @questions.each do |question| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">

            <%= link_to question.title, question %>
          </h4>
          <small>
            <%= question.body %>
          </small>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-4">
    <%=link_to "New Question", new_question_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/questions/new.html.erb
<h1>New Question</h1>

<div class="row">
  <div class="col-md-4">
    <p>Insert a new question rules are...</p>
    <ol>
      <li>Don't ask something you already know.</li>
      <li>Don't mock others with your questions.</li>
      <li>Don't be tepid ask.</li>
    </ol>
  </div>
  <div class="col-md-8">
    <%= form_for @question do |q| %>
      <div class="form-group">
        <%= q.label :title %>
        <%= q.text_field :title, class: 'form-control', placeholder: 'Enter the question title' %>
      </div>
      <div class="form-group">
        <%= q.label :body %>
        <%= q.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter the question contents" %>
      </div>
      <div class="form-group">
        <%= q.label :resolved, class: 'checkbox' do %>
          <%= q.check_box :resolved %> resolved
        <% end %>
      </div>
      <%= q.submit "Save", class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>



<div class="row">
  <div class="col-md-8">

    <p> <%= @question.body %> </p>
    <p> <%= @question.resolved %> </p>
  </div>
  <div class="col-md-4">
    <%= link_to "Edit Question", edit_question_path, class: 'btn btn-success' %>
    <%= link_to "New Question", new_question_path, class: 'btn btn-success'%>
    <%= link_to "Delete Question", @question, method: :delete, class: 'btn btn-danger', data: {confirm: "Are you sure you want to delete this question?"}%>
  </div>
</div>

app/views/questions/update.html.erb
<h1>Questions#update</h1>
<p>Find me in app/views/questions/update.html.erb</p>