config/routes.rb
Rails.application.routes.draw do


  resources :topics do
    resources :posts, except: [:index]
    resources :sponsored_posts, except: [:index]
  end
  resources :posts, only: [] do

    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end
  resources :advertisements

  resources :questions

  resources :users, only: [:new, :create, :show]
  post 'users/confirm' => 'users#confirm'

  resources :sessions, only: [:new, :create, :destroy]

  get 'about' => 'welcome#about'
#  get 'welcome/contact'

  get 'welcome/faq'

  root "welcome#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
# You advertisement show view depends on their being an advertisement made, and you don't seed the db with any advertisements
#
#
# [12:13]
# and for the other one i think it is because you don't define an index
#
#
# [12:16]
# and for you to make an advertisements view with resources it needs to be `resources advertisements` not `resources: advertisement`

app/models/advertisement.rb
class Advertisement < ApplicationRecord
end

app/controllers/advertisement_controller.rb
class AdvertisementController < ApplicationController
  def index
    @advertisements = Advertisement.all
  end

  def show
    @advertisement = Advertisement.find(params[:id])
  end

  def new
    @advertisement = Advertisement.new
  end

  def create
    @advertisement = Advertisement.new
    @advertisement.title = params[:advertisement][:title]
    @advertisement.copy = params[:advertisement][:copy]
    @advertisement.price = params[:advertisement][:price]

    if @advertisement.save

      flash[:notice] = "Advertisement was saved."
      redirect_to @advertisement

    else

      flash[:alert] = "There was an error saving your advertisement.  Please try again."
      render :new
    end
  end
end

app/controllers/advertisements_controller.rb
class AdvertisementsController < ApplicationController
  def index
    @advertisements = Advertisement.all
  end

  def show
    @advertisement = Advertisement.find(params[:id])
  end

  def new
    @advertisement = Advertisement.new
  end

  def create
    @advertisement = Advertisement.new
    @advertisement.title = params[:advertisement][:title]
    @advertisement.copy = params[:advertisement][:copy]
    @advertisement.price = params[:advertisement][:price]

    if @advertisement.save

      flash[:notice] = "Advertisement was saved."
      redirect_to @advertisement

    else

      flash[:alert] = "There was an error saving your advertisement.  Please try again."
      render :new
    end
  end
end

app/helpers/advertisements_helper.rb
module AdvertisementsHelper
end

app/views/advertisements/create.html.erb
<h1>Advertisements#create</h1>
<p>Find me in app/views/advertisements/create.html.erb</p>

app/views/advertisements/index.html.erb
<h1>Advertisements</h1>
<div class="row">
  <div class="col-md-8">

    <% @advertisements.each do |ad| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">

            <%= link_to "$#{ad.price}: #{ad.title}", ad %>
          </h4>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-4">
    <%=link_to "New Advertisement", new_advertisement_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/advertisements/new.html.erb
<h1>New Advertisement</h1>

<div class="row">
  <div class="col-md-4">
    <p>Create a new Ad:</p>

  </div>
  <div class="col-mid-8">
    <%= form_for @advertisement do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: 'Enter advertisement name' %>
      </div>
      <div class="form-group">
        <%= f.label :copy %>
        <%= f.text_area :copy, rows: 8, class: 'form-control', placeholder: "Enter advertisement description" %>
      </div>
      <div class="form-group">
        <%= f.label :price, class: "form-control" %>
          <%= f.text_area :price, class: "form-control", placeholder: "Enter the price" %>
      </div>
      <%= f.submit "Save", class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>

app/views/advertisements/show.html.erb
<h1><%= @advertisement.title %></h1>
<div class="row">
  <div class="col-md-8">
    <p> <%= @advertisement.copy %> </p>
    <p> <%= @advertisement.price %> </p>
  </div>
  <div class="col-md-4">
    <%= link_to "New", new_advertisement_path, class: "btn btn-success" %>
  </div>
</div>